name: CI
on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo python3 setup.py install
      - name: Perform checks
        run: cd ~/.hsf; sudo touch .accepted; python3 check.py
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo python3 setup.py install
      - name: Perform checks
        run: cd ~/.hsf; sudo touch .accepted; python3 check.py
