name: CI
on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo python3 setup.py install
      - name: Perform checks
        run: echo "accepted"
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo python3 setup.py install
      - name: Perform checks
        run: echo "accepted"
